### ISSUE TITLE
Erro nos links "Serviços aos cidadãos" e "Serviços às empresas""

### ISSUE THREAD

**Issue by almeidafab** [servicosgovbr/guia-de-servicos#284]

**Comment by cv** [comment]
```
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: 00000000-0000-0000-0000-000000000000 ERROR [http-nio-8080-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "conteudo.id" (fragments/resultado-busca-item:5)] with root cause
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 0): Property or field 'id' cannot be found on null
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:222) ~[spring-expression-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:93) ~[spring-expression-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:46) ~[spring-expression-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: at org.springframework.expression.spel.ast.PropertyOrFieldReference$AccessorLValue.getValue(PropertyOrFieldReference.java:372) ~[spring-expression-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:88) ~[spring-expression-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
May 14 13:41:06 ip-172-31-16-13.sa-east-1.compute.internal guia-de-servicos[8387]: at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:120) ~[spring-expression-4.1.6.RELEASE.jar!/:4.1.6.RELEASE]
```

**Comment by jeankirchner** [comment]
Correções feitas na #221
